esp32:  
  board: esp32dev  # Spécifie le modèle de la carte ESP32 (ESP32 DevKit V1 ici).
  framework:
    type: arduino  # Utilisation du framework Arduino, largement compatible avec ESPHome.

# Section commentée permettant l'importation d'une configuration complète depuis ESPHome.

packages:  # Inclusion d'une configuration externe pour modularité et réutilisation.
  twinsen68.enceinte_fil3d:  # Nom du package inclus.
    url: https://github.com/Twinsen68/enceinte_fil3d  # Lien vers le dépôt GitHub contenant la configuration de l’enceinte.
    file: enceinte_fil3d.yaml  # Fichier YAML spécifique inclus depuis le dépôt GitHub.
    ref: main  # Version spécifique du fichier à utiliser.

esphome:  # Configuration générale d'ESPHome pour cet appareil.
  name: enceintefil3d  # Nom de l'appareil défini dynamiquement via la variable "name".
  name_add_mac_suffix: false  # Empêche l'ajout d'un suffixe MAC au nom pour éviter les doublons sur le réseau.
  friendly_name: "Enceinte filament 3D controllée"  # Nom convivial affiché dans Home Assistant.

api:  # Active l’API ESPHome pour la communication avec Home Assistant.
  encryption:
    key: tsHqLo48mLGhWo/qQQrZUFdsEwuZcC1/BlUOXWExy14=  # Clé de chiffrement pour sécuriser les échanges.

wifi:  # Configuration du réseau Wi-Fi pour connecter l’ESP32.
  ssid: !secret wifi_ssid  # Renseignez ces valeurs dans votre fichier secrets.yaml.
  password: !secret wifi_password  # Voir le README pour les instructions de création.
